In [1]:
import xarray as xr
ds = xr.open_dataset('../data/merged/era5_waves_2014_2024.nc')
# Check which grid points have any valid data at all
import numpy as np
valid_points = (~np.isnan(ds['swh'].values)).any(axis=0)
print('Valid (ocean) points:', valid_points.sum(), 'of', valid_points.size)
print(valid_points.astype(int))


Valid (ocean) points: 13 of 25
[[0 1 1 1 1]
 [0 1 1 1 1]
 [0 0 0 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]
